apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../base/banking
patches:
- path: patch.yaml
images:
- name: lostud.azurecr.io/banking
  newName: lostud.azurecr.io/banking
  newTag: "1.59"
- name: lostud.azurecr.io/banking-api
  newName: lostud.azurecr.io/banking-api
  newTag: "1.9"
