apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-deployment 
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-app
  template:
    metadata:
      labels:
        env: prod
        app: banking-app
        app.kubernetes.io/name: banking-app
    spec:
      containers:
        - name: banking-app
          image: lostud.azurecr.io/banking:TAG
          ports:
            - containerPort: 80
              name: http-banking
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: ASPNETCORE_ENVIRONMENT
              value: Production