apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-deployment
  annotations:
    kubernetes.io/change-cause: "canary version for testing new features"
spec:
  template:
    metadata:
      labels:
        version: canary