apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-deployment
  annotations:
    kubernetes.io/change-cause: "canary version for testing new features"
spec:
  template:
    metadata:
      labels:
        version: canary
    spec:
      containers:
        - name: banking-app
          image: lostud.azurecr.io/banking:1.23