---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: documents-backup-cronjob
  namespace: default
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: mcr.microsoft.com/azure-cli
            env:
              - name: ACCOUNT_KEY
                valueFrom:
                  secretKeyRef:
                    name: azure-blob-secret
                    key: accountkey
            command: ["/bin/bash", "-c"]
            args:
              - |
                # Load Azure Blob Storage credentials from environment variables
                ACCOUNT_KEY=$(echo $ACCOUNT_KEY)

                # Define the path where the volume is mounted
                VOLUME_PATH="/mnt/data"  # Change this to your mount path
                DESTINATION_URL="https://backupstorageacctk8slos.blob.core.windows.net/backupdata"

                # Login to Azure Blob Storage using azcopy
                echo "Logging into Azure Blob Storage..."
                azcopy login --account-name backupstorageacctk8slos --account-key $ACCOUNT_KEY

                # Backup the Document volume data
                echo "Starting backup of Documents data..."
                azcopy cp "$VOLUME_PATH" "$DESTINATION_URL" --recursive
                echo "Backup completed successfully."
            volumeMounts:
            - name: documents-volume
              mountPath: /mnt/data
          restartPolicy: OnFailure
          volumes:
          - name: documents-volume
            persistentVolumeClaim:
              claimName: documents-pvc