apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: external-gateway
  namespace: aks-istio-ingress 
spec:
  selector:
    istio: aks-istio-ingressgateway-external
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: banking-virtual-service
  namespace: aks-istio-ingress 
spec:
  hosts:
  - "*"
  gateways:
  - external-gateway
  http:
  - match:
    - uri:
        regex: /(?i)banking.*
    route:
    - destination:
        host: banking-service.default.svc.cluster.local
        port:
          number: 80
        subset: stable
      weight: 90
    - destination:
        host: banking-service.default.svc.cluster.local
        port:
          number: 80
        subset: canary
      weight: 10 
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: banking-destination-rule
  namespace: default
spec:
  host: banking-service.default.svc.cluster.local
  subsets:
  - name: stable
    labels:
      version: stable
  - name: canary
    labels:
      version: canary
