---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali-virtual-service
  namespace: aks-istio-ingress
spec:
  hosts:
  - "*"
  gateways:
  - external-gateway
  http:
  - match:
    - uri:
        prefix: /kiali
    route:
    - destination:
        host: kiali.aks-istio-system.svc.cluster.local
        port:
          number: 20001