apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: istio-system  # Moved to istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-volume
              mountPath: /data
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"
      volumes:
        - name: prometheus-volume
          persistentVolumeClaim:
            claimName: prometheus-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
    name: prometheus-pvc
    namespace: istio-system  # Moved to istio-system
    labels:
      name: pvcprometheus
spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:   
       storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: istio-system
spec:
  ports:
  - name: web
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: prometheus